"""Report export system for the Neurology Intelligence Agent.

Supports four export formats:
  - export_markdown()      -- structured clinical Markdown report
  - export_json()          -- machine-readable JSON
  - export_pdf()           -- styled PDF via ReportLab Platypus
  - export_fhir_r4()       -- FHIR R4 DiagnosticReport Bundle

Plus specialised report generators:
  - export_stroke_report()          -- acute stroke triage report
  - export_dementia_evaluation()    -- dementia workup report
  - export_epilepsy_report()        -- epilepsy monitoring report
  - export_scale_report()           -- clinical scale calculation report

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import io
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Union

from .models import (
    ScaleResult,
    SeverityLevel,
    WorkflowResult,
)

logger = logging.getLogger(__name__)

VERSION = "1.0.0"


# ===================================================================
# SEVERITY COLOUR MAP
# ===================================================================

SEVERITY_COLORS: Dict[SeverityLevel, str] = {
    SeverityLevel.LOW:            "#2ECC71",  # green
    SeverityLevel.INFORMATIONAL:  "#3498DB",  # blue
    SeverityLevel.MODERATE:       "#F39C12",  # orange
    SeverityLevel.HIGH:           "#E74C3C",  # red
    SeverityLevel.CRITICAL:       "#8E44AD",  # purple
}


# ===================================================================
# REPORT TEMPLATES (Markdown fragments)
# ===================================================================

REPORT_TEMPLATES: Dict[str, str] = {
    "stroke": (
        "# Acute Stroke Triage Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Stroke Triage  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "dementia": (
        "# Dementia Evaluation Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Dementia Evaluation  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "epilepsy": (
        "# Epilepsy Monitoring Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Report Type:** Epilepsy Focus Localization  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "scale": (
        "# Clinical Scale Assessment Report\n\n"
        "**Patient ID:** {patient_id}  \n"
        "**Scale:** {scale_type}  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "workflow": (
        "# Neurology Clinical Workflow Report\n\n"
        "**Report Type:** {workflow_type} Workflow  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
}

_DISCLAIMER = (
    "\n\n---\n\n"
    "> **Disclaimer:** This report is generated by the HCLS AI Factory "
    "Neurology Intelligence Agent for clinical decision-support purposes "
    "only. It does not constitute medical advice and must be reviewed by "
    "qualified neurologists before any clinical action is taken. All "
    "scale scores and severity assessments are computed estimates.\n"
)


# ===================================================================
# HELPER FUNCTIONS
# ===================================================================


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_display() -> str:
    """Return a human-friendly UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _severity_badge(severity: SeverityLevel) -> str:
    """Return a Markdown badge string for a severity level."""
    colour = SEVERITY_COLORS.get(severity, "#95A5A6")
    label = severity.value.replace("_", " ").title()
    return f"![{label}](https://img.shields.io/badge/Severity-{label.replace(' ', '%20')}-{colour[1:]})"


def _severity_indicator(severity: SeverityLevel) -> str:
    """Return a text indicator for severity."""
    return f"[{severity.value.upper().replace('_', ' ')}]"


def _generate_filename(prefix: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{ts}.{extension}"


# ===================================================================
# MAIN EXPORTER CLASS
# ===================================================================


class NeuroReportExporter:
    """Multi-format report exporter for the Neurology Intelligence Agent.

    Accepts clinical response objects (``WorkflowResult``, ``ScaleResult``)
    and produces reports in Markdown, JSON, PDF, and FHIR R4 formats.

    Usage::

        exporter = NeuroReportExporter()
        md = exporter.export_stroke_report(workflow_result, patient_id="P-001")
        pdf_bytes = exporter.export_pdf(workflow_result)
        fhir = exporter.export_fhir_r4(workflow_result)
    """

    # -- Stroke Report --

    def export_stroke_report(
        self,
        result: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> str:
        """Export an acute stroke triage report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["stroke"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]

        findings, recommendations, severity, scale_results = self._extract_fields(result)

        lines.append(f"**Severity:** {_severity_badge(severity)}")
        lines.append("")

        if scale_results:
            lines.append("## Clinical Scale Scores\n")
            for sr in scale_results:
                if isinstance(sr, ScaleResult):
                    lines.append(f"- **{sr.scale_type.value.upper()}:** {sr.score}/{sr.max_score} -- {sr.interpretation}")
                elif isinstance(sr, dict):
                    lines.append(f"- **{sr.get('scale_type', 'unknown').upper()}:** {sr.get('score', 0)}/{sr.get('max_score', 0)} -- {sr.get('interpretation', '')}")
            lines.append("")

        if findings:
            lines.append("## Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Dementia Evaluation Report --

    def export_dementia_evaluation(
        self,
        result: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> str:
        """Export a dementia evaluation report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["dementia"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        findings, recommendations, severity, scale_results = self._extract_fields(result)

        lines.append(f"**Severity:** {_severity_badge(severity)}")
        lines.append("")

        if scale_results:
            lines.append("## Cognitive Assessment Scores\n")
            for sr in scale_results:
                if isinstance(sr, ScaleResult):
                    lines.append(f"- **{sr.scale_type.value.upper()}:** {sr.score}/{sr.max_score} -- {sr.interpretation}")
            lines.append("")

        if findings:
            lines.append("## Evaluation Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Clinical Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Epilepsy Report --

    def export_epilepsy_report(
        self,
        result: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> str:
        """Export an epilepsy monitoring report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["epilepsy"].format(
            patient_id=patient_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        findings, recommendations, severity, _ = self._extract_fields(result)

        lines.append(f"**Severity:** {_severity_badge(severity)}")
        lines.append("")

        if findings:
            lines.append("## EEG & Imaging Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Management Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Scale Report --

    def export_scale_report(
        self,
        scale_result: Union[ScaleResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> str:
        """Export a clinical scale calculation report as Markdown."""
        timestamp = _now_display()

        if isinstance(scale_result, ScaleResult):
            scale_type = scale_result.scale_type.value.upper()
            score = scale_result.score
            max_score = scale_result.max_score
            interpretation = scale_result.interpretation
            severity_category = scale_result.severity_category
            recommendations = scale_result.recommendations
        elif isinstance(scale_result, dict):
            scale_type = scale_result.get("scale_type", "unknown").upper()
            score = scale_result.get("score", 0)
            max_score = scale_result.get("max_score", 0)
            interpretation = scale_result.get("interpretation", "")
            severity_category = scale_result.get("severity_category", "")
            recommendations = scale_result.get("recommendations", [])
        else:
            scale_type = "UNKNOWN"
            score = 0
            max_score = 0
            interpretation = ""
            severity_category = ""
            recommendations = []

        header = REPORT_TEMPLATES["scale"].format(
            patient_id=patient_id,
            scale_type=scale_type,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"## Score: {score} / {max_score}\n")
        lines.append(f"**Interpretation:** {interpretation}  ")
        lines.append(f"**Severity Category:** {severity_category}\n")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Generic Markdown Export --

    def export_markdown(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        report_type: str = "workflow",
    ) -> str:
        """Export a generic workflow response as Markdown."""
        timestamp = _now_display()
        template_key = report_type if report_type in REPORT_TEMPLATES else "workflow"
        template = REPORT_TEMPLATES[template_key]

        header_vars: Dict[str, str] = {
            "timestamp": timestamp,
            "version": VERSION,
            "patient_id": "DEMO",
            "scale_type": "general",
        }

        if isinstance(response, WorkflowResult):
            header_vars["workflow_type"] = response.workflow_type.value.replace(
                "_", " "
            ).title()
        else:
            header_vars["workflow_type"] = report_type.replace("_", " ").title()

        lines: List[str] = [template.format(**header_vars)]

        findings, recommendations, severity, _ = self._extract_fields(response)

        if findings:
            lines.append("## Findings\n")
            for j, finding in enumerate(findings, 1):
                lines.append(f"{j}. {finding}")
            lines.append("")

        if recommendations:
            lines.append("## Recommendations\n")
            for j, rec in enumerate(recommendations, 1):
                lines.append(f"{j}. {rec}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- JSON Export --

    def export_json(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
    ) -> dict:
        """Export a clinical response as structured JSON."""
        if isinstance(response, WorkflowResult):
            data = response.model_dump()
        elif isinstance(response, dict):
            data = response
        else:
            data = {"raw": str(response)}

        return {
            "report_type": "neurology_workflow",
            "generated_at": _now_iso(),
            "version": VERSION,
            "data": data,
        }

    # -- PDF Export --

    def export_pdf(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        title: str = "Neurology Intelligence Report",
    ) -> bytes:
        """Export a clinical response as a PDF document.

        Requires ``reportlab`` to be installed. Returns empty bytes if
        the dependency is not available.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import (
                SimpleDocTemplate,
                Paragraph,
                Spacer,
            )
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            logger.warning(
                "reportlab not installed -- PDF export returning empty bytes"
            )
            return b""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Title
        story.append(Paragraph(title, styles["Title"]))
        story.append(Spacer(1, 12))

        # Timestamp
        story.append(
            Paragraph(
                f"Generated: {_now_display()} | Version: {VERSION}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 12))

        # Content
        findings, recommendations, _, _ = self._extract_fields(response)

        for finding in findings:
            story.append(Paragraph(f"Finding: {finding}", styles["Normal"]))
            story.append(Spacer(1, 6))
        for rec in recommendations:
            story.append(Paragraph(f"Recommendation: {rec}", styles["Normal"]))
            story.append(Spacer(1, 6))

        # Disclaimer
        story.append(Spacer(1, 24))
        story.append(
            Paragraph(
                "Disclaimer: This report is for clinical decision-support only.",
                styles["Italic"],
            )
        )

        doc.build(story)
        return buffer.getvalue()

    # -- FHIR R4 Export --

    def export_fhir_r4(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export as a FHIR R4 DiagnosticReport Bundle."""
        report_id = str(uuid.uuid4())
        timestamp = _now_iso()

        if isinstance(response, WorkflowResult):
            conclusion = "; ".join(response.findings[:3]) if response.findings else ""
            category_code = response.workflow_type.value
        elif isinstance(response, dict):
            findings = response.get("findings", [])
            conclusion = "; ".join(findings[:3]) if findings else ""
            category_code = response.get("workflow_type", "general")
        else:
            conclusion = str(response)
            category_code = "general"

        diagnostic_report = {
            "resourceType": "DiagnosticReport",
            "id": report_id,
            "status": "final",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://hcls-ai-factory.dev/neuro-agent",
                            "code": category_code,
                            "display": category_code.replace("_", " ").title(),
                        }
                    ]
                }
            ],
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "68604-8",
                        "display": "Neurology diagnostic study",
                    }
                ]
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": timestamp,
            "issued": timestamp,
            "conclusion": conclusion,
        }

        bundle = {
            "resourceType": "Bundle",
            "type": "document",
            "timestamp": timestamp,
            "entry": [
                {
                    "resource": diagnostic_report,
                    "fullUrl": f"urn:uuid:{report_id}",
                }
            ],
            "meta": {
                "profile": [
                    "http://hcls-ai-factory.dev/fhir/neurology-intelligence-report"
                ],
                "tag": [
                    {
                        "system": "http://hcls-ai-factory.dev/version",
                        "code": VERSION,
                    }
                ],
            },
        }

        return bundle

    # -- Private Helper --

    def _extract_fields(
        self, response: Union[WorkflowResult, Dict[str, Any]]
    ) -> tuple:
        """Extract common fields from a WorkflowResult or dict.

        Returns:
            Tuple of (findings, recommendations, severity, scale_results).
        """
        if isinstance(response, WorkflowResult):
            findings = response.findings
            recommendations = response.recommendations
            severity = response.severity
            scale_results = response.scale_results
        elif isinstance(response, dict):
            findings = response.get("findings", [])
            recommendations = response.get("recommendations", [])
            sev_str = response.get("severity", "informational")
            try:
                severity = SeverityLevel(sev_str)
            except (ValueError, KeyError):
                severity = SeverityLevel.INFORMATIONAL
            scale_results = response.get("scale_results", [])
        else:
            findings = []
            recommendations = []
            severity = SeverityLevel.INFORMATIONAL
            scale_results = []

        return findings, recommendations, severity, scale_results
